service: serverless


provider:
  name: aws
  runtime: python3.6


# you can add packaging information here
#package:
#  include:
#    - include-me.py
#    - include-me-dir/**
#  exclude:
#    - exclude-me.py
#    - exclude-me-dir/**


plugins:
  - serverless-python-requirements

functions:
  clients:
    handler: handler.clients
    events:
      - http:
          path: clients
          method: get
  cameras:
    handler: handler.cameras
    events:
      - http:
          path: cameras
          method: get
  client_cameras:
    handler: handler.client_cameras
    events:
      - http:
          path: client_cameras
          method: get
  stream_details:
    handler: handler.stream_details
    events:
      - http:
          path: stream_details
          method: get
  stream_metadata:
    handler: handler.stream_metadata
    events:
      - http:
          path: stream_metadata
          method: get
  server_metadata:
    handler: handler.server_metadata
    events:
      - http:
          path: stream_metadata
          method: get
